# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gisId', models.IntegerField()),
                ('longLat', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comId', models.IntegerField()),
                ('yearPlanted', models.IntegerField(null=True)),
                ('longLat', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(max_length=50)),
                ('scientificName', models.CharField(max_length=50)),
                ('genus', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('scarcity', models.IntegerField()),
                ('license', models.CharField(max_length=100, null=True)),
                ('artist', models.TextField(max_length=1024, null=True)),
                ('imageUrl', models.TextField(max_length=1024, null=True)),
                ('description', models.TextField(max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tree',
            name='treeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreeType'),
        ),
    ]
