# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_chair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='yearPlanted',
            field=models.IntegerField(null=True),
        ),
    ]
